# EdNet 테이블 만들기

KT1~KT4 전체 유저 CSV를 DuckDB 테이블로 적재합니다. **처음 한 번, 또는 쿼리를 고쳤을 때만 실행**합니다.

## 1. 테이블 생성 함수: `build_table(level)`
- `SQL/01_create_kt1.sql` 쿼리에서 테이블 이름과 폴더 경로만 `level` 인자로 뺐습니다.
- 테이블을 만든 뒤 앞 10행을 돌려줘 적재 결과를 바로 확인합니다.

In [1]:
import duckdb

con = duckdb.connect("../data/ednet.duckdb")

def build_table(level):
    table = level.lower()
    con.sql(f"""
    CREATE OR REPLACE TABLE {table} AS
    SELECT
        parse_filename(filename, true) AS user_id,
        * EXCLUDE (filename)
    FROM read_csv('../data/{level}/*.csv', filename = true);
    """)
    return con.sql(f"SELECT * FROM {table} LIMIT 10").df()

## 2. KT1~KT4 테이블 생성 및 확인

In [2]:
build_table("KT1")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  user_id      timestamp  solving_id question_id user_answer  elapsed_time
0      u1  1565096190868           1       q5012           b         38000
1      u1  1565096221062           2       q4706           c         24000
2      u1  1565096293432           3       q4366           b         68000
3      u1  1565096339668           4       q4829           a         42000
4      u1  1565096401774           5       q6528           b         59000
5      u1  1565096463370           6       q4793           a         58000
6      u1  1565096501746           7       q6488           a         35000
7      u1  1565097101361           8        q356           b         23000
8      u1  1565097171393           9       q1382           c         22000
9      u1  1565097240758          10        q830           b         25000

In [3]:
build_table("KT2")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  user_id      timestamp action_type item_id     source user_answer platform
0      u1  1565096151269       enter   b3544  diagnosis         NaN   mobile
1      u1  1565096187972     respond   q5012  diagnosis           b   mobile
2      u1  1565096194904      submit   b3544  diagnosis         NaN   mobile
3      u1  1565096195001       enter   b3238  diagnosis         NaN   mobile
4      u1  1565096218682     respond   q4706  diagnosis           c   mobile
5      u1  1565096223029      submit   b3238  diagnosis         NaN   mobile
6      u1  1565096223119       enter   b2898  diagnosis         NaN   mobile
7      u1  1565096290094     respond   q4366  diagnosis           b   mobile
8      u1  1565096295925      submit   b2898  diagnosis         NaN   mobile
9      u1  1565096296012       enter   b3361  diagnosis         NaN   mobile

In [4]:
build_table("KT3")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  user_id      timestamp action_type item_id     source user_answer platform
0      u1  1565096151269       enter   b3544  diagnosis         NaN   mobile
1      u1  1565096187972     respond   q5012  diagnosis           b   mobile
2      u1  1565096194904      submit   b3544  diagnosis         NaN   mobile
3      u1  1565096195001       enter   b3238  diagnosis         NaN   mobile
4      u1  1565096218682     respond   q4706  diagnosis           c   mobile
5      u1  1565096223029      submit   b3238  diagnosis         NaN   mobile
6      u1  1565096223119       enter   b2898  diagnosis         NaN   mobile
7      u1  1565096290094     respond   q4366  diagnosis           b   mobile
8      u1  1565096295925      submit   b2898  diagnosis         NaN   mobile
9      u1  1565096296012       enter   b3361  diagnosis         NaN   mobile

In [5]:
build_table("KT4")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,user_id,timestamp,action_type,item_id,cursor_time,source,user_answer,platform
0,u1,1565096151269,enter,b3544,<NA>,diagnosis,NaN,mobile
1,u1,1565096187972,respond,q5012,<NA>,diagnosis,b,mobile
2,u1,1565096194904,submit,b3544,<NA>,diagnosis,NaN,mobile
3,u1,1565096195001,enter,b3238,<NA>,diagnosis,NaN,mobile
4,u1,1565096218682,respond,q4706,<NA>,diagnosis,c,mobile
5,u1,1565096223029,submit,b3238,<NA>,diagnosis,NaN,mobile
6,u1,1565096223119,enter,b2898,<NA>,diagnosis,NaN,mobile
7,u1,1565096290094,respond,q4366,<NA>,diagnosis,b,mobile
8,u1,1565096295925,submit,b2898,<NA>,diagnosis,NaN,mobile
9,u1,1565096296012,enter,b3361,<NA>,diagnosis,NaN,mobile

## 3. 연결 종료
DuckDB는 쓰기 연결이 열려 있으면 다른 노트북에서 파일을 열 수 없어, 적재가 끝나면 연결을 닫습니다.

In [6]:
con.close()